### PR TITLE
fix inverse synctex problem Issue #15

### LINKED ISSUE #15: Inverse synctex doesn't work with Sioyek
This is what my configuration is. Only `--reuse-instance` removed (Sioyek v2.0.0 doesn't open if `--reuse-instance` used), everything else is default. Forward search is fine but when I enable synctex `F4` then right click it doesn't do anything.

OS: macOS 12.6.1
iTerm2, nvim v0.9.0-dev-76-g45cc5fd76-dirty

````
 texoutputext = "pdf",
  textopdfviewerlaunch = "sioyek --inverse-search 'nvim --headless -es --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%1'\"'\"',%2,%3)\"' %outputfile%",
  textopdfviewerrefresh = "none",
  textopdfforwardjump = "sioyek --inverse-search 'nvim --headless -es --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%1'\"'\"',%2,%3)\"' --forward-search-file %srcfile% --forward-search-line %line% %outputfile%",
  textopdfshorterror = "A=%outputfile% ; LOGFILE=\"${A%.pdf}.log\" ; rubber-info \"$LOGFILE\" 2>&1 | head -n 1",
  delay = 10
````

### PR DESCRIPTION
**Pull request by ChasingZenith**
Fix #15. 
The change is the parameters for `nvim`: `-es` is drop and `--cmd` is changed to `-c`. Both changes are necessary.
I don't know exactly which parameters do what. I just tune and get it. Please kindly check whether I will mess up other things.

### CODE REVIEW

**Comment by frabjous** [comment]
I don't understand the point of either change. The only difference is between `-c` and `--cmd` is whether or not other config files are sourced before the command, but the command in question requires everything it needs; I don't see why other configs would be needed. All `-es` does is make the command silent, and since it runs in the background, that shouldn't have any visible affect. Can someone post a *reproducible* set up in which these changes make a difference?

**Comment by ChasingZenith** [comment]
Also [vimtex sioyek configuration](https://github.com/lervag/vimtex/blob/a7b1654ef59bfd8c15ab3e0eb27451319174a131/autoload/vimtex/view/sioyek.vim#L38) use `-c` only. Maybe we can ask lervag for help.

**Comment by frabjous** [comment]
I'm not comfortable merging a pull request when I don't understand the problem the request is supposed to solve, cannot replicate it myself, and the changes seem to actually make things worse. 

Why load an entire configuration file before enacting the script's function when there is no need to? That'll just slow it down. Why not silence output that cannot be seen anyway? Again, leaving that output unsilenced is just likely to slow things down.

I made the choices I did for a reason, and I can't figure out why those choices are bad, so I just don't feel comfortable making changes.

Sorry -- I know you mean well -- but I don't see why vimtex doing something a certain way is of any relevance at all.

**Comment by ChasingZenith** [comment]
Nice to see your response. I doubt the problem may relate to whether the lua module `knaphelper` could be found. Now I try keep `-es` and `--cmd` and add one more `--cmd` to add `knap` in to `rtp`. This approach also works for me
```lua
        textopdfviewerlaunch = "sioyek %outputfile% --inverse-search 'nvim --headless -es --cmd \"set rtp+=~/.cache/vimfiles/repos/github.com/frabjous/knap/\" --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%1'\"'\"',%2,%3)\"' ",
```
I think the problem relates to how I the package managers load plugins. I am using [SpaceVim](https://github.com/SpaceVim/SpaceVim), which use [dein.vim](https://github.com/Shougo/dein.vim) as plugin manager.

**Comment by ChasingZenith** [comment]
Nice to see your response. I doubt the problem may relate to whether the lua module `knaphelper` could be found. Now I try keep `-es` and `--cmd` and add one more `--cmd` to add `knap` in to `rtp`. This approach also works for me
```lua
        textopdfviewerlaunch = "sioyek %outputfile% --inverse-search 'nvim --headless -es --cmd \"set rtp+=~/.cache/vimfiles/repos/github.com/frabjous/knap/\" --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%1'\"'\"',%2,%3)\"' ",
```
I think the problem relates to how I the package managers load plugins. I am using [SpaceVim](https://github.com/SpaceVim/SpaceVim), which use [dein.vim](https://github.com/Shougo/dein.vim) as plugin manager.

**Comment by frabjous** [comment]
Sorry it's taken me awhile to look at this. As a matter of principle, I'd strongly prefer not to hard code names of external programs in the main code like `xdotool` or `busctl`. You can create new settings for these things and allow the user to change them. I'm on wayland (hyprland not on GNOME) and can't use xdotool. The English in the suggested README change is poor. In general, I'm not very enthusiastic about merging this in this form. I can't really test it.

However, I'm not really using this plugin at all any more. If you wanted to take over the project, I'd consider handing it over. (You can change the name!)

**Pull request closed without merging**
